### ISSUE TITLE
Multidomains berücksichtigen.

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/pwa#5]
Hat jemand eine Idee wie das gehen könnte?

**Comment by AWqxKAWERbXo** [comment]
So wie yrewrite bei der sitemap.xml dynamisch die manifest-Datei ausgeben

**Comment by AWqxKAWERbXo** [comment]
Ich wollte mich nochmal zu Wort melden, da ich mich urspr. hier beteiligten wollte. Ich sehe das inzwischen nicht mehr als eigenes Addon, sondern gerade wegen der Multi-Domainfähigkeit als etwas, das man mit yrewrite_domain_settings (FOR) oder mit https://github.com/alexplusde/yrewrite_metainfo lösen kann. Bei letzterem ist bereits das meiste schlüsselfertig drin (Icons, UI-Settings)
