### ISSUE TITLE
Default fixed positionierter Button for iOS ein- und ausschaltbar

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/pwa#7]
Was genau meinst du damit @bitshiftersgmbh ?

**Comment by bitshiftersgmbh** [comment]
Das A2HS-Prompt (Add To Home Screen) gibt es nativ Stand heute nur für Android-Geräte, soweit ich weiß. Für Apple-Nutzer ist die Zugänglichkeit dazu - also zum Ablegen einer Seite auf dem Homescreen - damit deutlich schlechter gestaltet. Ich denke, das macht auch genau deshlab fast niemand.

Wir hatten für einen Pilotkunden serverseitig den Client ausgelesen und die Main Page (Template) bei iOS-Nutzern um eine fixed positionierte Lasche ergänzt die irgendwo oben rechts rum surft.

Ich denke, das könnte man per Checkbox einfach mit anbieten. Bei Klick öffnet sich ein Modal-Popup mit einer 5-Schritte-Anleitung. Das ist ja dann auch bei (fast) jedem iOS User identisch und bringt die iOS Nutzer überhaupt erst dazu zu verstehen, dass das geht und dass das auf dieser speziellen Seite und einen Sinn hat. Die Texte dafür kann man ja im 1. Step mal in die .lang-Files packen und später anbieten, stattdessen den Inhalt eines Artikels einzubinden (Link-Widget). So gibt man den Admin- und Redaktions-Menschen maximale Anpassungsmöglichkeiten.
